### PR TITLE
support runeterra worldwalkers

### PR DESCRIPTION
**Pull request by gabriel-gn**
Supporting Runeterra "region" and worldwalkers expansion for typescript.
Tests passed

### CODE REVIEW

**Comment by gabriel-gn** [comment]
@jcuker it is possible to check the generated package from the [NPM registry](https://www.npmjs.com/package/@gabrielgn-test/lor-deckcodes-ts)

**Comment by jcuker** [comment]
Oh wow! Thanks for the PR! What do you mean check the generated package? Do you mean just make sure that it gets updated?

**Comment by gabriel-gn** [comment]
Actually I just packed and deployed the result to test the package on some application running it. Hope it gets deployed to npm asap :D

**Comment by jcuker** [comment]
@gabriel-gn NPM update should be live - let me know!

**Pull request merged**
